/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreatePhaseConfig } from "./createPhaseConfig";
import type { CreatePhaseType } from "./createPhaseType";
import type { PhaseFeatureFlags } from "./phaseFeatureFlags";

export interface CreatePhase {
	type: CreatePhaseType;
	/**
	 * @minLength 1
	 * @maxLength 200
	 */
	title: string;
	/** @minimum 0 */
	sortOrder?: number;
	config?: CreatePhaseConfig;
	featureFlags?: PhaseFeatureFlags;
}
