/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDiscussionPhase } from './createDiscussionPhase';
import type { CreateSurveyPhase } from './createSurveyPhase';
import type { CreateVideoPhase } from './createVideoPhase';
import type { CreateVotingPhase } from './createVotingPhase';

export type CreatePhase = CreateVideoPhase | CreateDiscussionPhase | CreateVotingPhase | CreateSurveyPhase;
