/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTranscript {
  participantId?: string;
  phaseId?: string;
  /** @minLength 1 */
  content: string;
  language?: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  confidence?: number;
  isFinal?: boolean;
  /** @minimum 0 */
  startOffsetMs?: number;
  /** @minimum 0 */
  endOffsetMs?: number;
}
