/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateRoomStatus = typeof CreateRoomStatus[keyof typeof CreateRoomStatus];


export const CreateRoomStatus = {
  draft: 'draft',
  active: 'active',
  completed: 'completed',
  archived: 'archived',
} as const;
