/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateVotingPhaseType =
	(typeof CreateVotingPhaseType)[keyof typeof CreateVotingPhaseType];

export const CreateVotingPhaseType = {
	voting: "voting",
} as const;
