/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateSurveyPhaseType = typeof CreateSurveyPhaseType[keyof typeof CreateSurveyPhaseType];


export const CreateSurveyPhaseType = {
  survey: 'survey',
} as const;
