/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateVotingPhaseType } from "./createVotingPhaseType";
import type { VotingPhaseConfig } from "./votingPhaseConfig";
import type { VotingPhaseFeatureFlags } from "./votingPhaseFeatureFlags";

export interface CreateVotingPhase {
	type: CreateVotingPhaseType;
	/**
	 * @minLength 1
	 * @maxLength 200
	 */
	title: string;
	/** @minimum 0 */
	sortOrder?: number;
	config?: VotingPhaseConfig;
	featureFlags?: VotingPhaseFeatureFlags;
}
