/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDiscussionPhaseType } from './createDiscussionPhaseType';
import type { DiscussionPhaseConfig } from './discussionPhaseConfig';
import type { DiscussionPhaseFeatureFlags } from './discussionPhaseFeatureFlags';

export interface CreateDiscussionPhase {
  type: CreateDiscussionPhaseType;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /** @minimum 0 */
  sortOrder?: number;
  config?: DiscussionPhaseConfig;
  featureFlags?: DiscussionPhaseFeatureFlags;
}
