/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSurveyPhaseType } from "./createSurveyPhaseType";
import type { SurveyPhaseConfig } from "./surveyPhaseConfig";
import type { SurveyPhaseFeatureFlags } from "./surveyPhaseFeatureFlags";

export interface CreateSurveyPhase {
	type: CreateSurveyPhaseType;
	/**
	 * @minLength 1
	 * @maxLength 200
	 */
	title: string;
	/** @minimum 0 */
	sortOrder?: number;
	config?: SurveyPhaseConfig;
	featureFlags?: SurveyPhaseFeatureFlags;
}
