/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type CreatePhaseType = (typeof CreatePhaseType)[keyof typeof CreatePhaseType];

export const CreatePhaseType = {
	video: "video",
	discussion: "discussion",
	voting: "voting",
	survey: "survey",
} as const;
