/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateParticipant {
	/**
	 * @minLength 1
	 * @maxLength 50
	 */
	displayName: string;
}
