/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type DiscussionPhaseType = typeof DiscussionPhaseType[keyof typeof DiscussionPhaseType];


export const DiscussionPhaseType = {
  discussion: 'discussion',
} as const;
