/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export interface DiscussionSummary {
  id: string;
  roomId: string;
  phaseId: string;
  content: string;
  model: string;
  /** @nullable */
  promptTokens: number | null;
  /** @nullable */
  completionTokens: number | null;
  transcriptCount: number;
  createdAt: string;
  updatedAt: string;
}
