/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type GenerateSkippedReason =
	(typeof GenerateSkippedReason)[keyof typeof GenerateSkippedReason];

export const GenerateSkippedReason = {
	too_recent: "too_recent",
	no_new_transcripts: "no_new_transcripts",
} as const;
