/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiRoomsStatus = typeof GetApiRoomsStatus[keyof typeof GetApiRoomsStatus];


export const GetApiRoomsStatus = {
  draft: 'draft',
  active: 'active',
  completed: 'completed',
  archived: 'archived',
} as const;
