/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiRoomsRoomIdTransitionProposalsActive200ProposedByRole = typeof GetApiRoomsRoomIdTransitionProposalsActive200ProposedByRole[keyof typeof GetApiRoomsRoomIdTransitionProposalsActive200ProposedByRole];


export const GetApiRoomsRoomIdTransitionProposalsActive200ProposedByRole = {
  admin: 'admin',
  participant: 'participant',
} as const;
