/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiRoomsRoomIdTransitionProposalsActive200Status = typeof GetApiRoomsRoomIdTransitionProposalsActive200Status[keyof typeof GetApiRoomsRoomIdTransitionProposalsActive200Status];


export const GetApiRoomsRoomIdTransitionProposalsActive200Status = {
  open: 'open',
  approved: 'approved',
  rejected_by_admin: 'rejected_by_admin',
  expired: 'expired',
  cancelled: 'cancelled',
} as const;
