/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { JoinRoomRole } from "./joinRoomRole";

export interface JoinRoom {
	/**
	 * @minLength 1
	 * @maxLength 100
	 */
	displayName: string;
	role?: JoinRoomRole;
}
