/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type JoinRoomRole = typeof JoinRoomRole[keyof typeof JoinRoomRole];


export const JoinRoomRole = {
  participant: 'participant',
  facilitator: 'facilitator',
} as const;
