/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiPromptTemplatesTemplateId422 = {
	error: string;
	details?: unknown | null;
};
