/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { PhaseConfig } from "./phaseConfig";
import type { PhaseFeatureFlags } from "./phaseFeatureFlags";
import type { PhaseType } from "./phaseType";

export interface Phase {
	id: string;
	roomId: string;
	type: PhaseType;
	title: string;
	sortOrder: number;
	config: PhaseConfig;
	featureFlags: PhaseFeatureFlags;
	createdAt: string;
}
