/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export interface PhaseFeatureFlags {
  canSpeak?: boolean;
  canInterrupt?: boolean;
  canVote?: boolean;
  /** @exclusiveMinimum 0 */
  speakingTimeSec?: number;
  /** @exclusiveMinimum 0 */
  interruptionTimeSec?: number;
  /** @exclusiveMinimum 0 */
  interruptionCooldownSec?: number;
  /** @exclusiveMinimum 0 */
  maxInterruptions?: number;
  participantCanProposeTransition?: boolean;
  /** @minimum 0 */
  transitionMinDurationSec?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  transitionThreshold?: number;
  /** @exclusiveMinimum 0 */
  transitionVoteDurationSec?: number;
}
