/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiRoomsRoomIdTransitionProposals201ProposedByRole = typeof PostApiRoomsRoomIdTransitionProposals201ProposedByRole[keyof typeof PostApiRoomsRoomIdTransitionProposals201ProposedByRole];


export const PostApiRoomsRoomIdTransitionProposals201ProposedByRole = {
  admin: 'admin',
  participant: 'participant',
} as const;
