/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiRoomsRoomIdTransitionProposalsProposalIdVotes200ProposedByRole = typeof PostApiRoomsRoomIdTransitionProposalsProposalIdVotes200ProposedByRole[keyof typeof PostApiRoomsRoomIdTransitionProposalsProposalIdVotes200ProposedByRole];


export const PostApiRoomsRoomIdTransitionProposalsProposalIdVotes200ProposedByRole = {
  admin: 'admin',
  participant: 'participant',
} as const;
