/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiRoomsRoomIdTransitionProposalsProposalIdVotesBodyChoice =
	(typeof PostApiRoomsRoomIdTransitionProposalsProposalIdVotesBodyChoice)[keyof typeof PostApiRoomsRoomIdTransitionProposalsProposalIdVotesBodyChoice];

export const PostApiRoomsRoomIdTransitionProposalsProposalIdVotesBodyChoice = {
	yes: "yes",
	no: "no",
} as const;
