/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiRoomsRoomIdTransitionProposals201Status = typeof PostApiRoomsRoomIdTransitionProposals201Status[keyof typeof PostApiRoomsRoomIdTransitionProposals201Status];


export const PostApiRoomsRoomIdTransitionProposals201Status = {
  open: 'open',
  approved: 'approved',
  rejected_by_admin: 'rejected_by_admin',
  expired: 'expired',
  cancelled: 'cancelled',
} as const;
