/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export interface PromptTemplate {
	id: string;
	name: string;
	/** @nullable */
	description: string | null;
	systemPrompt: string;
	userPromptTemplate: string;
	language: string;
	isDefault: boolean;
	createdAt: string;
	updatedAt: string;
}
