/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export interface RecoverParticipant {
  /** @minLength 1 */
  recoveryCode: string;
}
