/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { RecordingStatus } from "./recordingStatus";

export interface Recording {
	id: string;
	roomId: string;
	egressId: string;
	status: RecordingStatus;
	/** @nullable */
	storageKey: string | null;
	/** @nullable */
	storageUrl: string | null;
	startedAt: string;
	/** @nullable */
	endedAt: string | null;
	/** @nullable */
	durationSec: number | null;
	/** @nullable */
	fileSize: number | null;
}
