/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type RecordingStatus = typeof RecordingStatus[keyof typeof RecordingStatus];


export const RecordingStatus = {
  recording: 'recording',
  completed: 'completed',
  failed: 'failed',
} as const;
