/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { SpeakerQueueStateCurrentSpeaker } from "./speakerQueueStateCurrentSpeaker";
import type { SpeakerQueueStateInterruptionsItem } from "./speakerQueueStateInterruptionsItem";
import type { SpeakerQueueStateQueueItem } from "./speakerQueueStateQueueItem";

export interface SpeakerQueueState {
	/** @nullable */
	currentSpeaker: SpeakerQueueStateCurrentSpeaker;
	queue: SpeakerQueueStateQueueItem[];
	interruptions: SpeakerQueueStateInterruptionsItem[];
}
