/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type SpeakerQueueStateCurrentSpeaker = {
	participantId: string;
	speakingUntil: number;
} | null;
