/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { SurveyAnswerItem } from './surveyAnswerItem';

export interface SubmitSurveyResponse {
  /** @minItems 1 */
  answers: SurveyAnswerItem[];
}
