/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { SurveyPhaseConfig } from "./surveyPhaseConfig";
import type { SurveyPhaseFeatureFlags } from "./surveyPhaseFeatureFlags";
import type { SurveyPhaseType } from "./surveyPhaseType";

export interface SurveyPhase {
	id: string;
	roomId: string;
	title: string;
	sortOrder: number;
	createdAt: string;
	type: SurveyPhaseType;
	config: SurveyPhaseConfig;
	featureFlags: SurveyPhaseFeatureFlags;
}
