/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type SurveyPhaseConfigQuestionsItemType =
	(typeof SurveyPhaseConfigQuestionsItemType)[keyof typeof SurveyPhaseConfigQuestionsItemType];

export const SurveyPhaseConfigQuestionsItemType = {
	text: "text",
	scale: "scale",
	choice: "choice",
} as const;
