/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type SurveyPhaseType = typeof SurveyPhaseType[keyof typeof SurveyPhaseType];


export const SurveyPhaseType = {
  survey: 'survey',
} as const;
