/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */
import type { Transcript } from "./transcript";

export interface TranscriptListResponse {
	transcripts: Transcript[];
}
