/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export interface Transcript {
	id: string;
	roomId: string;
	/** @nullable */
	participantId: string | null;
	/** @nullable */
	displayName: string | null;
	/** @nullable */
	phaseId: string | null;
	content: string;
	language: string;
	/** @nullable */
	confidence: number | null;
	isFinal: boolean;
	/** @nullable */
	startOffsetMs: number | null;
	/** @nullable */
	endOffsetMs: number | null;
	createdAt: string;
}
