/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePromptTemplate {
	/**
	 * @minLength 1
	 * @maxLength 200
	 */
	name?: string;
	/**
	 * @maxLength 2000
	 * @nullable
	 */
	description?: string | null;
	/** @minLength 1 */
	systemPrompt?: string;
	/** @minLength 1 */
	userPromptTemplate?: string;
	/**
	 * @minLength 1
	 * @maxLength 10
	 */
	language?: string;
	isDefault?: boolean;
}
