/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type UpdatePhaseType = (typeof UpdatePhaseType)[keyof typeof UpdatePhaseType];

export const UpdatePhaseType = {
	video: "video",
	discussion: "discussion",
	voting: "voting",
	survey: "survey",
} as const;
