/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type VideoPhaseType = (typeof VideoPhaseType)[keyof typeof VideoPhaseType];

export const VideoPhaseType = {
	video: "video",
} as const;
