/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Breakout Deliberation OS API
 * OpenAPI spec version: 1.0.0
 */

export type VotingPhaseType = (typeof VotingPhaseType)[keyof typeof VotingPhaseType];

export const VotingPhaseType = {
	voting: "voting",
} as const;
