import { env, fetchMock, SELF } from "cloudflare:test";
import { beforeAll, beforeEach, describe, expect, it } from "vitest";
import { cleanDatabase, createTestPhase, createTestRoom } from "./helpers/database";

const ADMIN_KEY = "test-admin-key";
const LIVEKIT_HOST = "https://test.livekit.example";

/**
 * Set up fetchMock interceptors for LiveKit API calls.
 * The livekit-server-sdk converts wss:// to http:// for REST API calls.
 */
function setupLiveKitFetchMocks() {
	// Intercept all requests to the LiveKit host
	const mockLivekit = fetchMock.get(LIVEKIT_HOST);

	// createRoom (Twirp POST)
	mockLivekit
		.intercept({ method: "POST", path: /^\/twirp\/livekit\.RoomService\/CreateRoom/ })
		.reply(200, JSON.stringify({ name: "mock-room", metadata: "" }), {
			headers: { "Content-Type": "application/json" },
		})
		.persist();

	// updateRoomMetadata (Twirp POST)
	mockLivekit
		.intercept({ method: "POST", path: /^\/twirp\/livekit\.RoomService\/UpdateRoomMetadata/ })
		.reply(200, JSON.stringify({ name: "mock-room", metadata: "" }), {
			headers: { "Content-Type": "application/json" },
		})
		.persist();

	// listRooms (Twirp POST)
	mockLivekit
		.intercept({ method: "POST", path: /^\/twirp\/livekit\.RoomService\/ListRooms/ })
		.reply(200, JSON.stringify({ rooms: [] }), {
			headers: { "Content-Type": "application/json" },
		})
		.persist();

	// updateParticipant (Twirp POST)
	mockLivekit
		.intercept({ method: "POST", path: /^\/twirp\/livekit\.RoomService\/UpdateParticipant/ })
		.reply(200, JSON.stringify({}), {
			headers: { "Content-Type": "application/json" },
		})
		.persist();
}

/** Helper: create a participant via the API and return its id */
async function createParticipantViaAPI(displayName = "TestUser"): Promise<string> {
	const res = await SELF.fetch("http://example.com/api/participants", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ displayName }),
	});
	const data = (await res.json()) as { id: string };
	return data.id;
}

beforeAll(() => {
	fetchMock.activate();
	fetchMock.disableNetConnect();
});

// fetchMock interceptors with .persist() remain active for the test file lifetime.
// The fetchMock itself is reset between test files automatically.

describe("POST /api/rooms/:roomId/join", () => {
	beforeEach(async () => {
		await cleanDatabase(env.DB);
		setupLiveKitFetchMocks();
	});

	it("should join an active room and return a token", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "join-room",
			title: "Join Room",
			status: "active",
		});
		const participantToken = await createParticipantViaAPI("Alice");

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/join`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ participantToken, role: "participant" }),
		});

		expect(response.status).toBe(200);
		const data = (await response.json()) as {
			token: string;
			livekitUrl: string;
			participantId: string;
			roomId: string;
		};
		// Token is a JWT string generated by livekit-server-sdk AccessToken
		expect(typeof data.token).toBe("string");
		expect(data.token.length).toBeGreaterThan(10);
		expect(data.participantId).toBe(participantToken);
		expect(data.roomId).toBe(roomId);
		expect(data.livekitUrl).toBeDefined();
	});

	it("should return 404 when room not found", async () => {
		const participantToken = await createParticipantViaAPI("Alice");

		const response = await SELF.fetch("http://example.com/api/rooms/nonexistent/join", {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ participantToken }),
		});

		expect(response.status).toBe(404);
	});

	it("should return 403 when room is not active", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "draft-room",
			title: "Draft Room",
			status: "draft",
		});
		const participantToken = await createParticipantViaAPI("Alice");

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/join`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ participantToken }),
		});

		expect(response.status).toBe(403);
		const data = (await response.json()) as { error: string };
		expect(data.error).toBe("Room is not active");
	});

	it("should use default role of participant when role not specified", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "default-role-room",
			status: "active",
		});
		const participantToken = await createParticipantViaAPI("Bob");

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/join`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ participantToken }),
		});

		expect(response.status).toBe(200);
		const data = (await response.json()) as { participantId: string };

		// Verify session_participation was persisted in DB with default role
		const sp = await env.DB.prepare("SELECT * FROM session_participations WHERE participant_id = ?")
			.bind(data.participantId)
			.first<{ role: string }>();
		expect(sp?.role).toBe("participant");
	});

	it("should accept facilitator role", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "facilitator-join-room",
			status: "active",
		});
		const participantToken = await createParticipantViaAPI("Facilitator");

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/join`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ participantToken, role: "facilitator" }),
		});

		expect(response.status).toBe(200);
	});

	it("should return 4xx for missing participantToken", async () => {
		const roomId = await createTestRoom(env.DB, { slug: "validation-join-room", status: "active" });

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/join`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({}),
		});

		expect(response.status).toBeGreaterThanOrEqual(400);
		expect(response.status).toBeLessThan(500);
	});

	it("should return 404 when participantToken does not exist", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "bad-token-room",
			status: "active",
		});

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/join`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ participantToken: "00000000-0000-0000-0000-000000000000" }),
		});

		expect(response.status).toBe(404);
		const data = (await response.json()) as { error: string };
		expect(data.error).toBe("Participant not found");
	});

	it("should reuse session_participation when joining with same participantToken again", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "rejoin-room",
			status: "active",
		});
		const participantToken = await createParticipantViaAPI("RejoiningUser");

		// First join
		const response1 = await SELF.fetch(`http://example.com/api/rooms/${roomId}/join`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ participantToken }),
		});
		expect(response1.status).toBe(200);

		// Second join with the same token
		const response2 = await SELF.fetch(`http://example.com/api/rooms/${roomId}/join`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ participantToken }),
		});
		expect(response2.status).toBe(200);

		// There should be only one session_participation record
		const rows = await env.DB.prepare(
			"SELECT * FROM session_participations WHERE participant_id = ? AND room_id = ?",
		)
			.bind(participantToken, roomId)
			.all();
		expect(rows.results.length).toBe(1);
	});
});

describe("POST /api/rooms/:roomId/activate", () => {
	beforeEach(async () => {
		await cleanDatabase(env.DB);
		setupLiveKitFetchMocks();
	});

	it("should activate a draft room", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "activate-room",
			title: "Activate Room",
			status: "draft",
		});

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/activate`, {
			method: "POST",
			headers: { "X-Admin-Key": ADMIN_KEY },
		});

		expect(response.status).toBe(200);
		const data = (await response.json()) as {
			success: boolean;
			roomId: string;
			livekitRoomName: string;
		};
		expect(data.success).toBe(true);
		expect(data.roomId).toBe(roomId);
		expect(data.livekitRoomName).toBe(`room-${roomId}`);

		// Verify status was updated in DB
		const room = await env.DB.prepare("SELECT status FROM rooms WHERE id = ?")
			.bind(roomId)
			.first<{ status: string }>();
		expect(room?.status).toBe("active");
	});

	it("should return 409 when room is already active", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "already-active-room",
			status: "active",
		});

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/activate`, {
			method: "POST",
			headers: { "X-Admin-Key": ADMIN_KEY },
		});

		expect(response.status).toBe(409);
		const data = (await response.json()) as { error: string };
		expect(data.error).toBe("Room is already active");
	});

	it("should return 404 when room not found", async () => {
		const response = await SELF.fetch("http://example.com/api/rooms/nonexistent/activate", {
			method: "POST",
			headers: { "X-Admin-Key": ADMIN_KEY },
		});

		expect(response.status).toBe(404);
	});

	it("should return 401 without admin key", async () => {
		const roomId = await createTestRoom(env.DB, { slug: "unauth-activate-room" });

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/activate`, {
			method: "POST",
		});

		expect(response.status).toBe(401);
	});
});

describe("POST /api/rooms/:roomId/phase/transition", () => {
	beforeEach(async () => {
		await cleanDatabase(env.DB);
		setupLiveKitFetchMocks();
	});

	it("should transition to a phase in an active room", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "transition-room",
			status: "active",
		});
		const phaseId = await createTestPhase(env.DB, roomId, {
			type: "discussion",
			title: "Discussion",
			featureFlags: { canSpeak: true },
		});

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/phase/transition`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
				"X-Admin-Key": ADMIN_KEY,
			},
			body: JSON.stringify({ phaseId }),
		});

		expect(response.status).toBe(200);
		const data = (await response.json()) as {
			success: boolean;
			phaseId: string;
			phaseType: string;
		};
		expect(data.success).toBe(true);
		expect(data.phaseId).toBe(phaseId);
		expect(data.phaseType).toBe("discussion");
	});

	it("should return 403 when room is not active", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "draft-transition-room",
			status: "draft",
		});
		const phaseId = await createTestPhase(env.DB, roomId, { type: "video", title: "Video" });

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/phase/transition`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
				"X-Admin-Key": ADMIN_KEY,
			},
			body: JSON.stringify({ phaseId }),
		});

		expect(response.status).toBe(403);
		const data = (await response.json()) as { error: string };
		expect(data.error).toBe("Room is not active");
	});

	it("should return 404 when phase not found", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "no-phase-transition-room",
			status: "active",
		});

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/phase/transition`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
				"X-Admin-Key": ADMIN_KEY,
			},
			body: JSON.stringify({ phaseId: "nonexistent-phase" }),
		});

		expect(response.status).toBe(404);
	});

	it("should return 404 when phase belongs to different room", async () => {
		const room1Id = await createTestRoom(env.DB, { slug: "trans-room-1", status: "active" });
		const room2Id = await createTestRoom(env.DB, { slug: "trans-room-2", status: "active" });
		const phaseId = await createTestPhase(env.DB, room1Id, { type: "discussion", title: "Phase" });

		const response = await SELF.fetch(`http://example.com/api/rooms/${room2Id}/phase/transition`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
				"X-Admin-Key": ADMIN_KEY,
			},
			body: JSON.stringify({ phaseId }),
		});

		expect(response.status).toBe(404);
	});

	it("should return 404 when room not found", async () => {
		const response = await SELF.fetch("http://example.com/api/rooms/nonexistent/phase/transition", {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
				"X-Admin-Key": ADMIN_KEY,
			},
			body: JSON.stringify({ phaseId: "some-phase" }),
		});

		expect(response.status).toBe(404);
	});

	it("should return 401 without admin key", async () => {
		const roomId = await createTestRoom(env.DB, {
			slug: "unauth-transition-room",
			status: "active",
		});
		const phaseId = await createTestPhase(env.DB, roomId, { type: "discussion", title: "Phase" });

		const response = await SELF.fetch(`http://example.com/api/rooms/${roomId}/phase/transition`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ phaseId }),
		});

		expect(response.status).toBe(401);
	});
});
